server:
  port: 8010
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:6868/eureka/
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/user
  application:
    name: server-feign

    redis:
      database: 0
      host: 127.0.0.1
      port: 6379
      password:
      timeout: 500
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 8
        min-idle: 0
#   mongodb:
#       uri: mongodb://name:password@localhost:27017/test
  thymeleaf: content-type=text/html

  feign:
    hystrix:
    enabled: true